import "./styles.css";

type Session={access_token:string;refresh_token:string};
type Child={student_id:string;school_name:string;full_name:string;student_number:string;class_name?:string|null;relationship:string};
type Timeline={student_id:string;timezone:string;events:Array<{id:string;type:string;occurred_at:string;is_late:boolean}>};
const root=document.querySelector<HTMLDivElement>("#app")!, API=(import.meta.env.VITE_API_BASE_URL as string|undefined)??"/api/v1", KEY="aksis.parent.session";
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]!);
const session=()=>{try{return JSON.parse(sessionStorage.getItem(KEY)??"null") as Session|null}catch{return null}};
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const s=session(),headers=new Headers(init.headers);headers.set("content-type","application/json");if(s)headers.set("authorization",`Bearer ${s.access_token}`);const r=await fetch(`${API}${path}`,{...init,headers});if(r.status===204)return undefined as T;const body=await r.json();if(!r.ok||!body.success)throw new Error(body.error?.message??"Layanan tidak tersedia");return body.data as T}
function loginView(){root.innerHTML=`<main class="login"><div class="hero"><div class="brand">A <span>AKSIS Keluarga</span></div><h1>Dekat dengan perjalanan anak, setiap hari.</h1><p>Kehadiran dan aktivitas sekolah dalam satu tampilan yang tenang dan aman.</p></div><form id="login"><small>PORTAL ORANG TUA</small><h2>Masuk ke akun Anda</h2><div id="error"></div><label>Email<input name="email" type="email" required autocomplete="username"/></label><label>Kata sandi<input name="password" type="password" minlength="8" required autocomplete="current-password"/></label><button>Masuk <span>→</span></button></form></main>`;document.querySelector<HTMLFormElement>("#login")!.onsubmit=async e=>{e.preventDefault();const f=e.currentTarget as HTMLFormElement,d=new FormData(f);try{const data=await request<{session:Session}>("/auth/login",{method:"POST",body:JSON.stringify({email:d.get("email"),password:d.get("password")})});sessionStorage.setItem(KEY,JSON.stringify(data.session));await dashboard()}catch(x){document.querySelector("#error")!.textContent=x instanceof Error?x.message:"Gagal masuk"}}}
async function dashboard(){try{const children=await request<Child[]>("/parent/children");if(!children.length){root.innerHTML=layout(`<section class="empty"><span>♡</span><h2>Hubungkan anak Anda</h2><p>Masukkan token aman yang diberikan sekolah. Pencarian nama tidak pernah memberikan akses.</p><button id="link">Hubungkan anak</button></section>`);bind();document.querySelector("#link")!.addEventListener("click",linkView);return}const selected=children[0]!,timeline=await request<Timeline>(`/parent/children/${selected.student_id}/today`);root.innerHTML=layout(`<section class="welcome"><p>Selamat datang kembali</p><h1>${esc(selected.full_name)}</h1><div><span>${esc(selected.class_name??"Belum ada kelas")}</span><span>${esc(selected.school_name)}</span></div></section><section class="today"><div class="section-head"><div><small>HARI INI</small><h2>Aktivitas anak</h2></div><span>${new Intl.DateTimeFormat("id-ID",{day:"numeric",month:"long"}).format(new Date())}</span></div>${timeline.events.length?`<div class="timeline">${timeline.events.map(ev=>`<article><time>${new Intl.DateTimeFormat("id-ID",{hour:"2-digit",minute:"2-digit"}).format(new Date(ev.occurred_at))}</time><i></i><div><strong>${ev.type.endsWith("check_in")?"Tiba di sekolah":"Pulang dari sekolah"}</strong><p>${ev.is_late?"Tercatat terlambat":"Terverifikasi oleh gerbang sekolah"}</p></div><b>✓</b></article>`).join("")}</div>`:`<div class="empty compact"><span>○</span><h3>Belum ada aktivitas hari ini</h3><p>Aktivitas terverifikasi akan muncul otomatis.</p></div>`}</section><section class="privacy"><strong>Privasi terjaga</strong><p>Anda hanya melihat anak yang terhubung melalui token resmi sekolah.</p></section>`);bind()}catch{sessionStorage.removeItem(KEY);loginView()}}
function layout(content:string){return `<div class="shell"><header><div class="brand">A <span>AKSIS</span></div><button id="logout" aria-label="Keluar">↪</button></header><main>${content}</main><nav><a class="active">⌂<span>Beranda</span></a><a id="add">＋<span>Tambah anak</span></a><a>◎<span>Profil</span></a></nav></div>`}
function bind(){document.querySelector("#logout")?.addEventListener("click",async()=>{const s=session();try{if(s)await request("/auth/logout",{method:"POST",body:JSON.stringify({refresh_token:s.refresh_token})})}catch{}sessionStorage.removeItem(KEY);loginView()});document.querySelector("#add")?.addEventListener("click",linkView)}
function linkView(){root.innerHTML=layout(`<form class="link-card" id="link-form"><small>TAUTAN AMAN</small><h2>Hubungkan anak</h2><p>Gunakan token satu kali dari admin sekolah.</p><div id="error"></div><label>Nama orang tua<input name="name" required maxlength="200"/></label><label>Nomor telepon<input name="phone" maxlength="32"/></label><label>Token sekolah<input name="token" required minlength="32" autocomplete="off"/></label><button>Verifikasi & hubungkan</button><button type="button" class="ghost" id="cancel">Batal</button></form>`);bind();document.querySelector("#cancel")!.addEventListener("click",()=>void dashboard());document.querySelector<HTMLFormElement>("#link-form")!.onsubmit=async e=>{e.preventDefault();const d=new FormData(e.currentTarget as HTMLFormElement);try{await request("/parent/link",{method:"POST",body:JSON.stringify({token:d.get("token"),full_name:d.get("name"),phone:d.get("phone")||null})});await dashboard()}catch(x){document.querySelector("#error")!.textContent=x instanceof Error?x.message:"Token tidak valid"}}}
if("serviceWorker"in navigator&&import.meta.env.PROD)void navigator.serviceWorker.register("/sw.js");session()?void dashboard():loginView();
