import { gateIntro, gateHelp } from "../../shared/portal-ui";
import "./styles.css";

import { PortalSession } from "../../shared/portal-session";
import { setupInstallPrompt, offerInstall } from "../../shared/install-prompt";
const portal = new PortalSession("PARENT", import.meta.env.VITE_API_BASE_URL ?? "/api/v1");
setupInstallPrompt("Portal Orang Tua", import.meta.env.BASE_URL, import.meta.env.PROD);
type Child={student_id:string;school_name:string;full_name:string;student_number:string;class_name?:string|null;relationship:string};
type Timeline={student_id:string;timezone:string;events:Array<{id:string;type:string;occurred_at:string;is_late:boolean;extra_info?:string}>};
const root=document.querySelector<HTMLDivElement>("#app")!;
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]!);
const request = <T>(path:string, init:RequestInit={}) => portal.request<T>(path, init);
function loginView(message = "Pindai QR dari admin sekolah untuk membuka aktivitas anak Anda.") {
  root.innerHTML = `<main class="login"><header><div class="brand"><img src="/logo.png" alt="AKSIS"><b>AKSIS · Keluarga</b></div></header><section class="portal-gate">${gateIntro('Dekat dengan hari anak Anda', 'Ikuti kehadiran dan aktivitas anak melalui informasi terverifikasi dari sekolah.')}<p role="status">${esc(message)}</p><button id="retry-portal">Coba lagi</button>${gateHelp}</section></main>`;
  document.getElementById("retry-portal")!.onclick = () => void start();
}
async function start() {
  loginView("Membuka akses sekolah…");
  try {
    if (!await portal.start()) { loginView(); return; }
    const hasChildren = await dashboard();
    if (hasChildren) offerInstall();
  } catch (error) { loginView(error instanceof Error ? error.message : "Belum dapat terhubung."); }
}
let selectedChildId = "";
async function dashboard(): Promise<boolean> {try{const children=await request<Child[]>("/parent/children");if(!children.length){root.innerHTML=layout(`<section class="empty"><span>♡</span><h2>Hubungkan anak Anda</h2><p>Masukkan NISN dan Tanggal Lahir untuk memverifikasi data siswa secara mandiri.</p><button id="link">Hubungkan anak</button></section>`);bind();document.querySelector("#link")!.addEventListener("click",linkView);return false;}const selected=children.find(child => child.student_id === selectedChildId) ?? children[0]!; selectedChildId = selected.student_id; const timeline=await request<Timeline>(`/parent/children/${selected.student_id}/today`);root.innerHTML=layout(`${children.length > 1 ? `<label class="child-picker">Anak yang ditampilkan<select id="child-picker">${children.map(child=>`<option value="${esc(child.student_id)}" ${child.student_id===selectedChildId?"selected":""}>${esc(child.full_name)}</option>`).join("")}</select></label>` : ""}<section class="welcome"><p>Selamat datang kembali</p><h1>${esc(selected.full_name)}</h1><div><span>${esc(selected.class_name??"Belum ada kelas")}</span><span>${esc(selected.school_name)}</span></div></section><section class="today"><div class="section-head"><div><small>HARI INI</small><h2>Aktivitas anak</h2></div><span>${new Intl.DateTimeFormat("id-ID",{day:"numeric",month:"long",timeZone:timeline.timezone}).format(new Date())}</span></div>${timeline.events.length?`<div class="timeline">${timeline.events.map(ev=>{
let title = "Aktivitas", desc = ev.extra_info || "", icon = "✓", color = "#146c43";
if (ev.type === "attendance.check_in") { title = "Tiba di sekolah"; desc = ev.is_late ? "Tercatat terlambat" : "Terverifikasi oleh gerbang sekolah"; icon = "🏢"; }
else if (ev.type === "attendance.check_out") { title = "Pulang dari sekolah"; desc = "Terverifikasi oleh gerbang sekolah"; icon = "🏠"; }
else if (ev.type === "waste.transaction") { title = "Bank Sampah"; icon = "♻"; color = "#214b38"; }
else if (ev.type === "library.visit") { title = "Perpustakaan"; icon = "📚"; color = "#0f5132"; }
else if (ev.type === "extracurricular.attendance") { title = "Ekstrakurikuler"; icon = "🏅"; color = "#243b67"; }
return `<article><time>${new Intl.DateTimeFormat("id-ID",{hour:"2-digit",minute:"2-digit",timeZone:timeline.timezone}).format(new Date(ev.occurred_at))}</time><i style="border-color:${color}"></i><div><strong style="color:${color}">${title}</strong><p>${esc(desc)}</p></div><b style="color:${color}">${icon}</b></article>`;
}).join("")}</div>`:`<div class="empty compact"><span>○</span><h3>Belum ada aktivitas hari ini</h3><p>Aktivitas terverifikasi akan muncul otomatis.</p></div>`}</section><section class="privacy"><strong>Privasi terjaga</strong><p>Anda hanya melihat anak yang terhubung melalui data resmi sekolah.</p></section>`);bind(); return true;}catch(error){loginView(error instanceof Error ? error.message : "Belum dapat memuat aktivitas.");throw error;}}
function layout(content:string){return `<div class="shell"><header><div class="brand" style="display: flex; align-items: center; gap: 0.75rem;"><img src="/logo.png" alt="AKSIS Logo" style="height: 32px; width: auto; object-fit: contain; filter: drop-shadow(0px 0px 4px rgba(255, 255, 255, 0.8));"><div><b>AKSIS</b><small class="portal-school">Portal Orang Tua</small></div></div><button id="logout" aria-label="Keluar">↪</button></header><main>${content}</main><nav aria-label="Navigasi portal"><button id="home" class="active">⌂<span>Beranda</span></button><button id="add">＋<span>Tambah anak</span></button><button id="profile">◎<span>Akses saya</span></button></nav></div>`}
function bind(){document.querySelector("#home")?.addEventListener("click",()=>void dashboard());document.querySelector("#profile")?.addEventListener("click",()=>{root.innerHTML=layout(`<section class="profile-card"><small>AKSES ORANG TUA</small><h1>Akses saya</h1><dl><div><dt>Sekolah</dt><dd>${esc(portal.context?.school_name)}</dd></div><div><dt>Privasi</dt><dd>Hanya anak yang telah terhubung</dd></div></dl><p>Akses ini berasal dari QR Admin Sekolah. Hubungi sekolah jika informasi anak perlu diperbarui.</p></section>`);bind();document.querySelector('#home')?.classList.remove('active');document.querySelector('#profile')?.classList.add('active');});document.querySelector<HTMLSelectElement>('#child-picker')?.addEventListener('change',event=>{selectedChildId=(event.target as HTMLSelectElement).value;void dashboard();});document.querySelector("#logout")?.addEventListener("click",async()=>{await portal.logout().catch(()=>undefined);loginView("Anda sudah keluar. Pindai QR untuk masuk kembali.")});document.querySelector("#add")?.addEventListener("click",linkView)}
function linkView(){root.innerHTML=layout(`<form class="link-card" id="link-form"><small>TAUTAN AMAN</small><h2>Hubungkan anak</h2><p>Gunakan NISN dan Tanggal Lahir anak Anda.</p><div id="error"></div><label>Nama orang tua / wali<input name="name" required maxlength="200"/></label><label>NISN Siswa<input name="nisn" required maxlength="50"/></label><label>Tanggal Lahir<input type="date" name="dob" required placeholder="YYYY-MM-DD"/></label><button>Verifikasi & hubungkan</button><button type="button" class="ghost" id="cancel">Batal</button></form>`);bind();document.querySelector("#home")?.classList.remove("active");document.querySelector("#add")?.classList.add("active");document.querySelector("#cancel")!.addEventListener("click",()=>void dashboard());document.querySelector<HTMLFormElement>("#link-form")!.onsubmit=async e=>{e.preventDefault();const d=new FormData(e.currentTarget as HTMLFormElement);try{await request("/parent/link",{method:"POST",body:JSON.stringify({nisn:d.get("nisn"),dob:d.get("dob"),full_name:d.get("name")})});await dashboard();offerInstall();}catch(x){document.querySelector("#error")!.textContent=x instanceof Error?x.message:"Data tidak ditemukan atau tidak valid"}}}
void start();
